#######################################################################
# Program:
#    Checkpoint 04b, more classes
#    Brother Walker, CS165
# Author:
#    Scott Currell
# Summary: 
#    Summaries are not necessary for checkpoint assignments.
########################################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : date.h date.cpp check04b.cpp
	g++ date.cpp check04b.cpp
