###############################################################
# Program:
#     Assignment 05, Order Tracking
#     Brother Walker, CS165
# Author:
#     Scott Currell
# Summary:
#     eCommerce product inventory. Collect customer, address, product, and
# 		order data. Print that data to the screen to verify classes function
#		as expected.
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp address.h address.cpp customer.h customer.cpp order.h order.cpp assign05.cpp
	g++ product.cpp address.cpp customer.cpp order.cpp assign05.cpp

